# Auto-generated by compose2nix.
# 手动集成了 tmpfiles 目录创建逻辑
{
  pkgs,
  lib,
  config,
  ...
}: {
  # --- 自动创建持久化目录逻辑 ---
  systemd.tmpfiles.rules = [
    "d /var/lib/booklore 0755 root root -"
    "d /var/lib/booklore/data 0755 root root -"
    "d /var/lib/booklore/books 0755 root root -"
    "d /var/lib/booklore/bookdrop 0755 root root -"
    # MariaDB 容器内部用的是 PUID 1000，所以这里把权限给到 1000
    "d /var/lib/booklore/mariadb 0755 1000 1000 -"
  ];

  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."booklore" = {
    image = "ghcr.io/booklore-app/booklore:latest";
    environment = {
      "BOOKLORE_PORT" = "6060";
      "DATABASE_PASSWORD" = "xufeng233";
      "DATABASE_URL" = "jdbc:mariadb://mariadb:3306/booklore";
      "DATABASE_USERNAME" = "booklore";
      "GROUP_ID" = "0";
      "TZ" = "Asia/Tokyo";
      "USER_ID" = "0";
    };
    volumes = [
      "/var/lib/booklore/bookdrop:/bookdrop:rw"
      "/var/lib/booklore/books:/books:rw"
      "/var/lib/booklore/data:/app/data:rw"
    ];
    ports = [
      "6060:6060/tcp"
    ];
    dependsOn = [
      "mariadb"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=wget -q -O - http://localhost:6060/api/v1/healthcheck"
      "--health-interval=1m0s"
      "--health-retries=5"
      "--health-start-period=1m0s"
      "--health-timeout=10s"
      "--network-alias=booklore"
      "--network=booklore_default"
    ];
  };

  systemd.services."podman-booklore" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-booklore_default.service"
    ];
    requires = [
      "podman-network-booklore_default.service"
    ];
    partOf = [
      "podman-compose-booklore-root.target"
    ];
    wantedBy = [
      "podman-compose-booklore-root.target"
    ];
  };

  virtualisation.oci-containers.containers."mariadb" = {
    image = "lscr.io/linuxserver/mariadb:11.4.5";
    environment = {
      "MYSQL_DATABASE" = "booklore";
      "MYSQL_PASSWORD" = "xufeng233";
      "MYSQL_ROOT_PASSWORD" = "xufeng233";
      "MYSQL_USER" = "booklore";
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Asia/Tokyo";
    };
    volumes = [
      "/var/lib/booklore/mariadb:/config:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"mariadb-admin\", \"ping\", \"-h\", \"localhost\"]"
      "--health-interval=5s"
      "--health-retries=10"
      "--health-timeout=5s"
      "--network-alias=mariadb"
      "--network=booklore_default"
    ];
  };

  systemd.services."podman-mariadb" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-booklore_default.service"
    ];
    requires = [
      "podman-network-booklore_default.service"
    ];
    partOf = [
      "podman-compose-booklore-root.target"
    ];
    wantedBy = [
      "podman-compose-booklore-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-booklore_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f booklore_default";
    };
    script = ''
      podman network inspect booklore_default || podman network create booklore_default
    '';
    partOf = ["podman-compose-booklore-root.target"];
    wantedBy = ["podman-compose-booklore-root.target"];
  };

  # Root service
  systemd.targets."podman-compose-booklore-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
