# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: {
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."calibre-web-automated" = {
    image = "crocodilestick/calibre-web-automated:latest";
    environment = {
      "DOCKER_MODS" = "linuxserver/mods:universal-calibre";
      "PGID" = "100";
      "PUID" = "1000";
      "TZ" = "Asia/Tokyo";
    };
    volumes = [
      "/var/lib/calibre-web-automated/config:/config:rw"
      "/var/lib/calibre-web-automated/cwa-book-ingest:/cwa-book-ingest:rw"
      "/var/lib/calibre-web-automated/library:/books:rw"
    ];
    ports = [
      "8083:8083/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=calibre-web-automated"
      "--network=calibre-web_default"
    ];
  };
  systemd.services."podman-calibre-web-automated" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-calibre-web_default.service"
    ];
    requires = [
      "podman-network-calibre-web_default.service"
    ];
    partOf = [
      "podman-compose-calibre-web-root.target"
    ];
    wantedBy = [
      "podman-compose-calibre-web-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-calibre-web_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f calibre-web_default";
    };
    script = ''
      podman network inspect calibre-web_default || podman network create calibre-web_default
    '';
    partOf = ["podman-compose-calibre-web-root.target"];
    wantedBy = ["podman-compose-calibre-web-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-calibre-web-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
